paginate: 10
include: [assets, css, js, img, do-not-track]

archive_dir: archive
category_dir: category
tag_dir: tag

pygments: true

permalink: /archive/:year/:month/:day/:title

ga_tracking_code: UA-34829303-1
ga_domain: blog.orestes.io

url: http://blog.orestes.io
media_url: /media
source_url: http://github.com/orestes/blog.orestes.io
title: Orestes Carracedo

author_name: Orestes Carracedo
author_email: orestes.ca@gmail.com
copyright_years: 2009-2013

feed_title: Orestes Carracedo
feed_url: http://feeds.feedburner.com/orestes/blog
